### ISSUE TITLE
一个恶心的公司 

### ISSUE THREAD

**Issue by aaawhz** [ElemeFE/node-interview#18]

**Comment by ucev** [comment]
卧槽，你这是犯贱啊

**Comment by hackjutsu** [comment]
不知道发生什么事，但是建议直接拉黑该用户，以免再发这种无意义的issue

**Comment by Lellansin** [comment]
本 repo 的主体是技术. 如果对于该公司有什么问题你可以拨打 `12315` 可以联系新闻媒体, 也可以上微博去艾特人民网等渠道来维护你的利益. Github 应该是程序员讨论技术的净土.

**Comment by aaawhz** [comment]
恶心的垃圾公司         一群苍蝇在这里....       走了..

**Comment by Lellansin** [comment]
@aaawhz  你提的 issue 描述不准确, 含有一些无意义的修饰词, 使得我们无法理解你的需求. 不过目测与当前 repo 无关. 如果你希望在 Github 上讨论公司的问题, 你可以先把自己的逻辑理清, 然后将具体情况拆分好, 并附上你自身的详细的环境信息以及真实的用例情况, 然后去这里提 PR/issue: https://github.com/shengxinjing/programmer-job-blacklist (对这方面事情感兴趣的同学也推荐去这个 repo)
