### ISSUE TITLE
关于nodeJs连接池有个问题

### ISSUE THREAD

**Issue by zcs19871221** [ElemeFE/node-interview#19]
https://github.com/ElemeFE/node-interview/blob/master/sections/network.md#agent

这里有段话是说 【当 keepAlive 为 true 是, 由于 socket 复用, 之前的事件监听如果忘了清除很容易导致重复监听】实际上不管是true还是false只要使用了连接池(agent)，而且实际连接数超过了maxSocket设置的上限的话，socket都会复用。keepalive选项开的话，实际调用的是socke.setKeepAlive。作用就是激活操作系统的tcp协议的keepalive功能，在keepAliveMsecs时间之后会由系统发送keepalive嗅探包，具体的间隔根据操作系统定义。剩下keepalive的操作就都交给操作系统了。

**Comment by Lellansin** [comment]
Hi @zcs19871221 , 你说的问题我之前确实没有注意到, 但是感觉还有点疑问, 出于严谨的考虑, 想考证下 node 的源代码, 并实验一下在去修改原文, 所以反馈比较慢. 当然如果你能写个博文列举一下就更好了, 我会在原文中引用的 (非请求, 仅建议).

**Comment by zcs19871221** [comment]
@Lellansin 我又重新读了下源代码，写了下例子。我说的基本是对的，详情看这个https://github.com/zcs19871221/mydoc/blob/master/nodejsAgent.md    包含node源代码和我写的例子

**Comment by Lellansin** [comment]
Hi, 这个问题已经 ack 目前由 @wangdashuaihenshuai  同学来根据跟进

**Comment by wangdashuaihenshuai** [comment]
说的没错，如果还有未处理的请求，也是会复用 socket，没有未处理的请求的时候，才会根据 keepAlive 来判断是否销毁 Scoket。

【当 keepAlive 为 true 是, 由于 socket 复用, 之前的事件监听如果忘了清除很容易导致重复监听】
将改为
【当 keepAlive 为 true 或者长时间大量请求时, 由于 socket 一直未销毁, 之前的事件监听如果忘了清除很容易导致重复监听】

附加信息【会出现此问题的 node 版本为 6.8.1（包括）到6.10（不包括）。】

**Comment by zcs19871221** [comment]
@wangdashuaihenshuai @Lellansin 求引用

**Comment by wangdashuaihenshuai** [comment]
已经将这次讨论加入pr了 https://github.com/ElemeFE/node-interview/pull/24/files 。

**Comment by Lellansin** [comment]
@zcs19871221 @wangdashuaihenshuai  这边再修改了一下描述, 帮忙 review 下

**Comment by Lellansin** [comment]
先关闭了, feel free to reopen
