### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by visualfanatic** [ElemeFE/node-interview#2]
It would be helpful to have an English version. If not, what is the reason for the english repo name and description?

**Comment by cctv1005s** [comment]
A english repo name  is required in github.

**Comment by limichange** [comment]
`node-mianshi` 2333333

**Comment by xilihuasi** [comment]
mianshi - -

**Comment by MIKUScallion** [comment]
Will there be a fontend-interview in the future ? I Admire ElemeFE. ^_^

**Comment by sofish** [comment]
@mmoaay @Leopoldthecoder

**Comment by Yuanbin-xavier** [comment]
This is an excellent program, I had learned a lot from it, and I hope the author can keep serializing

**Comment by Leopoldthecoder** [comment]
@sofish 感觉可以由 @mmoaay 的团队先翻译，如果对 JS 的一些内容有疑问，我可以校对。

**Comment by mmoaay** [comment]
哦可，可以按照 element 的规范来，上次杨老师已经给了很好的示例了

**Comment by pdf13** [comment]
I would love an english version too.

**Comment by fuchao2012** [comment]
@cinwell.li  docsify 来解决这个问题就很赞啊。本身这个库就很赞了。替广大 markdown 程序猿感谢你 👍

**Comment by arjunmayilvaganan** [comment]
Hello all,

Asking this I'm unclear. Is an English version coming anytime soon?

**Comment by Lellansin** [comment]
@arjunmayilvaganan  We'd accomplish the Chinese version in a week, and after the adjustment, English version will get in plan (maybe 2~3 week after), and the process & date detail will come with it.

**Comment by arjunmayilvaganan** [comment]
@Lellansin thanks for the clarification.

**Comment by Lellansin** [comment]
English version plan has been started. feel free to reopen this issue.
