### ISSUE TITLE
Timers 章节里引用的阮老师的文章其内容不够严谨，建议更换官方的英文版文档

### ISSUE THREAD

**Issue by Becavalier** [ElemeFE/node-interview#21]
https://github.com/ElemeFE/node-interview/blob/master/sections/event-async.md#timers

“JavaScript 运行机制详解：再谈Event Loop (中文)“  这篇文章之前被 朴老师 评论过，内容有很多地方不严谨。

FYI：
http://blog.csdn.net/lin_credible/article/details/40143961

**Comment by Lellansin** [comment]
Hi, 关于 Event loop 文中已经留了一篇官方的文章, 请问另外还有比较推荐的官方的 Event loop 的文章吗. 另外中文的介绍, 当时我直接取了 Google 第一个, 如果有比较好的中文的文章也欢迎推荐

**Comment by cuyl** [comment]
推荐一篇[Tasks, microtasks, queues and schedules](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)

**Comment by Lellansin** [comment]
done
