### ISSUE TITLE
关于"Javascript 基础问题"中"内存释放"的问题

### ISSUE THREAD

**Issue by CoderIvan** [ElemeFE/node-interview#25]
> 比如上述情况中 unused 的函数中持有了 originalThing 的引用, 使得每次旧的对象不会释放从而导致内存泄漏 (例子出自《Node.js 垃圾回收》)

根据我的理解，这个答案是不完整的，可以试着把unused的定义注释掉，一样会存在内存泄露的问题

真实的原因是这个：
![image](https://cloud.githubusercontent.com/assets/7960859/24533167/7cdde58c-15f8-11e7-9366-738731c22bca.png)

这是由于`lexical scope`所引起的，所有function的定义都会使用到originalThing形成闭包，而originalThing是指向上一个闭包的，产生一条引用链

而且现在的V8引擎已经优化了这问题（但不是完美解决这个问题）

本人其实也是一知半解描述不清楚，在这就尝试抛砖引玉了

**Comment by Lellansin** [comment]
Cool, 最近比较忙, 放假会抽时间验证一下

**Comment by Hack-yao** [comment]
这里会产生内存泄漏的原因是：unused和someMethod的闭包都是在共同的replaceThing函数下产生的。所以他们享有同样的闭包，也就是说someMethod的闭包中也有对originalThing 的引用。theThing引用someMethod，someMethod中维持对originalThing的引用。故而产生了内存泄漏。。。。个人的理解

**Comment by liuxiansenjs** [comment]
我感觉在每一次replaceThing执行时unused函数都创建一次，当函数结束后，没有任何全局变量能引用unused所以unused不会造成内存泄露呀。每次函数执行时，每次theThing都是重复被赋值，someMethod也没有引用函数内的数据，我感觉不会造成内存泄露呀。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Memory_Management

可能我我刚接触两个月，银行工作想转行，水平太渣，看不懂TT

**Comment by zhengyhn** [comment]
Hi all, 我把这个例子在本地试了，发现内存的确是会增长，但是后面会被释放，我使用了7.9.0, 4.4.0和0.10.35三个版本测试，都是会自动释放的

**Comment by meiwhu** [comment]
你们都试过么。。。现在不会内存泄漏了。。。
> Now, Chrome’s V8 JavaScript engine is apparently smart enough to keep variables out of the lexical environment if they aren’t used by any closures - from the Meteor blog.

**Comment by Lellansin** [comment]
循环引用的问题早已在 V8 层面上处理了。处理方式是直接从根节点上开始变量，如果循环引用的对象没法从根节点遍历到就会被标记成待释放的对象然后等待 GC。

Feel free to reopen
