### ISSUE TITLE
模块中的全局变量问题

### ISSUE THREAD

**Issue by InSpirit12** [ElemeFE/node-interview#35]
`模块`章节：  
`如果 a.js require 了 b.js, 那么在 b 中定义全局变量 t = 111 能否在 a 中直接打印出来?`  
原文写的是可以,并给了示例，但在本机测试会显示referenceerror: t is not defined   
是否还有其他的限制条件呢？

**Comment by Lellansin** [comment]
@InSpirit12  刚试了下，用 8.1.1 都可以，你的代码？

**Comment by InSpirit12** [comment]
确实如此
