### ISSUE TITLE
将基础类型包装也不能以引用的方式传递

### ISSUE THREAD

**Issue by BarryZhan** [ElemeFE/node-interview#45]
在引用传递的问题中

> 通过将基础类型包装(boxing) 可以以引用的方式传递.

虽然传递的是指向数字对象的引用复本，但我们并不能通过它来更改其中的基本类型值：

``` javascript
    function foo (x) {
      x = x + 1
      console.log(x) // 3 
    }

    var a = new Number(1) // Object(a)也一样

    foo(a)
    console.log(a) // 是2，不是3
```

**Comment by Lellansin** [comment]
x = x + 1 是得到了一个新的值，与旧的引用无关了，你可以这样看

    function foo (x) {
      x.test = 1
      console.log(x) 
    }

    var a = new Number(1) // Object(a)也一样

    foo(a)
    console.log(a)
