### ISSUE TITLE
[请教] : mongodb 的一个问题?

### ISSUE THREAD

**Issue by lijinke666** [ElemeFE/node-interview#51]
我是一个新手, 在平时开发中 不管是 mysql 的 `Sequelize` 库 还是  `mongoose` 
比如一个简单的 查询
```js
const find = async ()=> await MODEL.find({xx})
```
现在需要 遍历 改变一些数据
```js
(await find()).map(  v=> v.cname = v.name )
```
发现没生效, 把这个 v 打印出来 发现 除了自己的数据之外 , 还有  mongoose 的一些 proto

于是我用很傻的方法 
```js
const data = JSON.parse(JSON.stringify(await find() ))
```

这样获取到数据 就是干净的
但如果我不 处理这个数据  直接 `res.send(await find())` (express) 也是没问题的
这是为什么呢?

**Comment by Lellansin** [comment]
这是因为这两个库都给表的数据加了数据结构，所以查询出来的并不直接是数据，而是带结构的数据，如果你不按他们的接口去修改数据，是没有效果的。你 stringify 的话会调用它数据结构中内置的 toJSON 就变成纯的 JSON 数据了。直接 res.send(await find()) 那是 send 里面碰到对象会调用对象的 toString 类方法。那个时候也触发它自身的 toJSON

**Comment by lijinke666** [comment]
原来是这样, 感谢你的回答,也感谢你们这个教程,学到了很多 :+1:  
晚上回去点一份 饿了么外卖 已表敬意 :)

**Comment by 0neSe7en** [comment]
也可以用`toObject`。或者在query的后面加上`lean()`可以去掉那些字段，但是同样也失去了`save`等方法。但是`lean()`可以明显的提高速度。

**Comment by Lellansin** [comment]
Feel free to reopen

**Comment by deepred5** [comment]
说下sequlize，比如你上面说的问题：
```
let data = await MODEL.findAll();
```
现在你想给data数组里的每个数据添加一个属性，如果你直接这样写:
```
data.forEach((item) => {
    item.num = 1;
});
```
然后把data返回给客户端，客户端是获取不到新增的num属性的。

解决方法：

方法一：
```
data.forEach((item) => {
    item.dataValues.num = 1;
});
```
只能给每个数据的dataValues添加属性

方法二：
```
let data = await MODEL.findAll({raw: true});
data.forEach((item) => {
    item.num = 1;
});
```
查询的时候添加查询条件`raw: true`，之后你就可以直接添加属性了
