### ISSUE TITLE
reduceAsync

### ISSUE THREAD

**Issue by zyl1314** [ElemeFE/node-interview#53]
```
Array.prototype.reduce = async function(callback, initValue) {
    const ctx = this;
    const len = this.length;
    let result = null;

    async function next(preValue, curValue, index, arr) {
        let temp = await callback(...arguments);
        if (index == len-1) return temp;
        return next(temp, ctx[index+1], index+1, ctx);
    }

    if (initValue) {
        result = await next(initValue, ctx[0], 0, ctx);
    } else {
        result = await next(ctx[0], ctx[1], 1, ctx);
    }
   
    return result;
}

// example
const arr = [1, 2, 3];
const sum = arr.reduce(async function(pre, cur) {
    const temp = await new Promise(function(resolve, reject) {
        setTimeout(function() {
            resolve(pre + cur);
        }, 1000)
    })
    return temp;
});

sum.then(function(result) {
    console.log(result);
})
```
这么写可以不

**Comment by jituanlin** [comment]
不是很明白题意，普通的reduce函数就支持呀，使用如下
const R = require("ramda")

const asyncFn = n => Promise.resolve(n)

R.reduce(
    async (accP, elm) => (await accP) + (await asyncFn(elm)),
    Promise.resolve(0),
    [1, 2, 3, 4]
).then(result => console.log(result))

**Comment by Lellansin** [comment]
题目的场景可以是有 n 个（如一百个） DB 要合并，DB 中有一些 table 里面有一些字段是 unique 的，例如名字等。那么合并数据库的时候就只能依次两两合并处理冲突之后作为一份新的数据继续跟下一个 DB 处理冲突合并。本质上就是异步的 reduce，不是 reduce 的异步。

补充一下，之前出这个题时候主流是用 Promise 实现。 async/await 还没有流行。相当于是考验 Promise 的一个题目。

**Comment by jituanlin** [comment]
谢谢了，明白题意了
如果是两个两个合并，那上面我给的代码就应该是错的，应该用类似**归并**的做法,类似[sacala中的fold](https://stackoverflow.com/questions/16111440/scala-fold-vs-foldleft)
