### ISSUE TITLE
几个杂务

### ISSUE THREAD

**Issue by GongT** [ElemeFE/node-interview#54]
今天刷招聘信息有人发这个给我问我懂不懂。。。相见恨晚啊。。。
感谢大佬们的工作，顺便求大佬们带带我= =。

### 一个小问题
[sections/zh-cn/common.md#L50](https://github.com/ElemeFE/node-interview/blob/master/sections/zh-cn/common.md#引用传递) 这里提到一个StackOverflow的问题，但是这个答案排序是动态的，看了一下应该是指的Shog9的那个，我这里现在看他排第二，引用答案可以点它的share按钮。

**然后我的建议其实是：这个是不是应该翻译一下😂😂😂**

*这个知识点我觉得很尴尬，以前我给别人讲过这个问题，可能我表达的不好，对方根本没懂。如果和略懂C语言（指针）的人讲就特别容易。*
*面试的时候我也不敢说，就怕面试官以为我装逼把我踢了。。。我也很绝望啊。。。*

### 关于Let It Crash 的求助
大佬们有没有尝试把这个思想推广一下？有没有什么可行的办法。我曾经在之前的2家公司推广过，但都失败了。。。

**Comment by Lellansin** [comment]
SO 上那个问题，其实排名前几的都讲的挺有道理，是不是有点钦定的感觉[眼睛]...

另外 Let It Crash 那个，要推的话推荐用集群的方式，重点是保证集群（应用）可用，而不是单个节点可用（Um, 就像 erlang 一样）

**Comment by Lellansin** [comment]
定时清理.

Feel free to reopen.
