### ISSUE TITLE
同源策略解释有误

### ISSUE THREAD

**Issue by FrankKai** [ElemeFE/node-interview#55]
Network模块的问题：什么是跨域请求？如何允许跨域？答案存在错误。
https://github.com/ElemeFE/node-interview/blob/master/sections/zh-cn/network.md#q-cors
出于安全考虑, 默认情况下使用 XMLHttpRequest 和 Fetch 发起 HTTP 请求必须遵守同源策略, **即只能向相同域名请求. 向不同域名的请求**被称作跨域请求 (cross-origin HTTP request). 可以通过设置 CORS headers 即 Access-Control-Allow- 系列来允许跨域. 

同源是指：相同协议，相同域名，相同端口。

而不仅仅是相同域名。

**Comment by Lellansin** [comment]
已修改

**Comment by pavelShen** [comment]
修改后还是把相同协议给漏了，http和https也算跨域的

**Comment by Lellansin** [comment]
特地这么写的，不是漏，参照上下文改的，按照原文的上下文指定讨论了 http（上下文是 HTTP -> Header -> HTTP 的同源策略），否则加上去可能增加读者的阅读负担（同一个地方写的像教科书一样塞太多的概念）。

有同学比较关心的话，这边加个注解（[已更新](https://github.com/ElemeFE/node-interview/commit/67e5b990e422c3620d0ecfd34314584c1fefd81e)），如果有好的描述，欢迎提 PR。

**Comment by Lellansin** [comment]
Feel free to reopen.
