### ISSUE TITLE
发现一个小问题

### ISSUE THREAD

**Issue by alwxkxk** [ElemeFE/node-interview#61]
首先十分感谢团队做了这份让大家有机会从中学习。

1.在 事件异步.并行/并发里发现一个问题：
原文：Node.js 通过事件循环来挨个抽取事件队列中的一个个 Task 执行, 从而避免了传统的多线程情况下 2个队列对应 1个咖啡机的时候**上线文切换**以及资源争抢/同步的问题, 所以获得了高并发的成就。

**上线文切换**是否为**上下文切换**？

**Comment by Lellansin** [comment]
已修改~

Free feel to reopen.
