### ISSUE TITLE
关于Io那个章节的一个问题

### ISSUE THREAD

**Issue by youth7** [ElemeFE/node-interview#64]
在`如何同步的获取用户的输入?`那个问题中您写到：
>而要同步读取, 则是不用异步的 read 接口, 而是用同步的 readSync 接口去读取 stdin 的数据即可实现. 

从文档中可知`Readable.read`本来就是同步的，为何你说它是异步接口呢？

**Comment by Lellansin** [comment]
Readable 继承自 EventEmitter，其本身的代码和事件触发都是同步的，异步的地方是读写文件进入 io 操作时通过 libuv 发出去的。

**Comment by Lellansin** [comment]
Feel free to reopen.
