### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lijinke666** [ElemeFE/node-interview#66]
![image](https://user-images.githubusercontent.com/21015895/38184074-db2d7c24-3677-11e8-8ad7-806e368a1357.png)
在阅读您的文章时 
[Network > 粘包 >方案1 ](https://elemefe.github.io/node-interview/#/sections/zh-cn/network)
少了一个 `不` 字

**Comment by Lellansin** [comment]
Thx, fixed.
