### ISSUE TITLE
对于内存释放的例子，感觉不是很好理解

### ISSUE THREAD

**Issue by aogg** [ElemeFE/node-interview#7]
对于内存释放的例子，感觉不是很好理解（每次都是一个例子）。不知道下面理解是否正确？
运行时添加 -expose-gc的node命令行参数。

https://github.com/ElemeFE/node-interview/blob/master/sections/js-basic.md#内存释放
```node
// 错误
var theThing = null;
var replaceThing = function () {
    let 泄漏变量 = theThing;
    let unused = function () {
        if (泄漏变量)
            console.log("hi")
    };
    // 不断修改引用
    theThing = {
        longStr: new Array(1000000).join('*'),
        someMethod: function () {
            console.log('a')
        }
    };

    global.gc();
    // 每次输出的值会越来越大
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);
```

正确修改1
```node
// 正确
var theThing = null;
var replaceThing = function () {
    let unused = function () {
        if (theThing)
            console.log("hi")
    };
    // 不断修改引用
    theThing = {
        longStr: new Array(1000000).join('*'),
        someMethod: function () {
            console.log('a')
        }
    };

    global.gc();
    // 每次输出的值会保持不变
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);
```

正确修改2
```node
// 正确
var theThing = null;
var replaceThing = function () {
    let 泄漏变量 = theThing;
    let unused = function () {
        if (泄漏变量)
            console.log("hi")
    };
    // 不断修改引用
    theThing = {
        longStr: new Array(1000000).join('*'),
        someMethod: function () {
            console.log('a')
        }
    };

    泄漏变量 = null;
    // unused = null; // 不行匿名函数依然存在

    global.gc();
    // 每次输出的值会保持不变
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);
```

**Comment by hyj1991** [comment]
这个其实你从这方面理解：在V8当前版本中，闭包对象是当前作用域中的所有内部函数作用域共享的，并且这个当前作用域的闭包对象中除了包含一条指向上一层作用域闭包对象的引用外，其余的存储的变量引用一定是当前作用域中的所有内部函数作用域中使用到的变量。

这样就可以解释泄漏的原因了：在 ```replaceThing``` 定义的函数作用域中，由于 ```unused``` 表达式定义的函数使用到了 ```泄漏变量```，因此 ```泄漏变量``` 被 ```replaceThing``` 函数作用域的闭包对象持有了，从而导致 ```theThing``` 对象中的 ```someMethod``` 函数隐式地持有了 ```泄漏变量``` 的引用。

这样就造成了 ```theThing->someMethod->泄漏变量->上一次theThing->...``` 的循环引用，因此产生了内存泄漏，而且 ```thThing. longStr``` 又是一个大字符串，所以每次访问后内存上升明显。

其实这里要解决也比较简单：一种就是你的第二种修改方式，手动在每次调用完成后把 ```泄漏变量 = null;```，另一种是干掉 ```unused`` 函数和 ```泄漏变量``` 间的闭包引用，这样 ```someMethod``` 和 ```replaceThing``` 定义的函数作用域生成的闭包对象中就不会有 ```泄漏变量```了，也就没有内存泄漏了。

**Comment by aogg** [comment]
@hyj1991 学到了，没留意到theThing.someMethod函数

根据你上面说的第二种取消必包引用，补充如下：（不知理解对不）
```node
var theThing = '';
var replaceThing = function () {
    let 泄漏变量 = !!theThing;
    let unused = function () {
        if (泄漏变量)
            console.log("hi")
    };

    theThing = {
        longStr: new Array(1000000).join('*'),
        someMethod: function () {
            console.log('a')
        }
    };

    global.gc();
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);
```


但是这样theThing.someMethod方法依然占用两个变量（但不会内存上升），是不是应该每次都要在最后调用
```node
    泄漏变量 = null;
    unused = null;
```
1、这样看来是不是应该减少匿名函数使用，或有什么更好的方法？
2、如果是面向对象，都用类会不会就好点，将定义外部变量和定义类分开（减少[副作用](https://laravel-china.org/topics/2078#23-副作用)）？




然后不断的学习，又发现一个解决方案：（利用let的块级作用域）
```node
var theThing = '';
var replaceThing = function () {
    {
        let 泄漏变量 = theThing; // 如果是var则依然会内存上升
        let unused = function () {
            if (泄漏变量)
                console.log("hi")
        };
    }

    // 不断修改引用
    theThing = {
        longStr: new Array(1000000).join('*'),
        someMethod: function () {
            console.log('a')
        }
    };

    global.gc();
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);
```

**Comment by Lellansin** [comment]
Hi, 还可以这样:

```javascript
let unused = function (内部变量) {
    if (内部变量)
        console.log("hi")
};
```
这样 immutable 一下貌似也可以了

**Comment by hyj1991** [comment]
你的两种修改方式其实和提问的本意有一些区别了。
首先你的第一种方式，其实相当于断掉了 ```泄漏变量``` 和 ```theThing``` 的引用，所以不会泄露。我当时的意思其实是这样处理：

```
let unused = function (泄漏变量) {
    if (泄漏变量)
        console.log("hi")
};
```

这样 ```unused``` 表达式和外部的 ```泄漏变量``` 的闭包引用切断了，那么同一个作用域下的 ```someMethod``` 方法持有的指向 ```replaceThing``` 函数作用域的闭包对象中就不会有 ```泄露变量``` 了，从而一次interval中的引用链 ```theThing->someMethod``` 就结束了，内存不会泄露。

至于你写的第二种处理方式，是因为let的块级作用域，导致整个 ```replaceThing``` 中的作用域结构完全变掉了，即：

```
{
        let 泄漏变量 = theThing; // 如果是var则依然会内存上升
        let unused = function () {
            if (泄漏变量)
                console.log("hi")
        };
    }
```
这个一整个部分和 ```someMethod``` 的函数作用域共享同一个 ```replaceThing``` 函数作用域生成的闭包对象了，这里显然  ```unused``` 和 ```someMethod``` 不会再共享同一个闭包对象了，所以也不会泄露。

**Comment by aogg** [comment]
@hyj1991 对，应该减少函数对外部变量的依赖，好像js对这种处理方式用的会比较多，再补充个完整的：
```node
var theThing = '';
var replaceThing = function () {
    const 泄漏变量 = theThing;
    const unusedSync = function (泄漏变量) { // 同步执行执行
        if (泄漏变量)
            console.log("hii")
    };
    unusedSync(泄漏变量);
    
    
    const unused = 泄漏变量 => function () { // 异步执行，就多一层
        if (泄漏变量)
            console.log("hi")
    };
    setTimeout(unused(泄漏变量), 0);

    theThing = {
        longStr: new Array(1000000).join('*'),
        someMethod: function () {
            console.log('a')
        }
    };


    global.gc();
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);
```

**Comment by gjc9620** [comment]
也许可以这样？
```
// 错误
var theThing = null;
var replaceThing = function () {
  let 泄漏变量 = theThing;
  let unused = function () {
    if (泄漏变量)
      console.log("hi")
  };
  theThing = theThing ||  {}
  theThing.longStr = new Array(1000000).join('*');
  theThing.someMethod = function () {
    // console.log('a')
  };
  // 不断修改引用
  // theThing = {
  //   // longStr: new Array(1000000).join('*')
  //   // ,
  //   someMethod: function () {
  //     // console.log('a')
  //   }
  // };
  
  global.gc();
  // 每次输出的值会越来越大
  console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 100);

```

**Comment by hyj1991** [comment]
@gjc9620 你那样改没用的，和原来的泄漏例子原因一模一样，你可以把 ```new Array(1000000)``` 的值增大，比如改成 ```new Array(10000000)```，马上就能看到内存超过1.4G爆掉：

```bash
<--- Last few GCs --->

   23762 ms: Mark-sweep 1319.7 (1333.6) -> 1319.7 (1333.6) MB, 3.3 / 0.0 ms [allocation failure] [GC in old space requested].
   23765 ms: Mark-sweep 1319.7 (1333.6) -> 1319.7 (1333.6) MB, 3.4 / 0.0 ms [allocation failure] [GC in old space requested].
   23769 ms: Mark-sweep 1319.7 (1333.6) -> 1319.7 (1329.6) MB, 3.3 / 0.0 ms [last resort gc].
   23771 ms: Mark-sweep 1319.7 (1329.6) -> 1319.7 (1329.6) MB, 2.2 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x172bb50cfb51 <JS Object>
    2: _onTimeout(aka replaceThing) [/Users/huangyijun/git/examples/testGC.js:26] [pc=0x33a658b4c11b] (this=0x1c01c359f811 <a Timeout with map 0x367a85a1c569>)
    3: ontimeout(aka ontimeout) [timers.js:365] [pc=0x33a658b4bc35] (this=0x172bb5004381 <undefined>,timer=0x1c01c359f811 <a Timeout with map 0x367a85a1c569>)
    4: tryOnTimeout(aka tryOnTimeout) [timers.js:237] [pc=0x33a658b4b90b] (thi...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleySmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)1> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleySmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)1> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleySmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)1> >::SetLengthImpl(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSArray>, unsigned int, v8::internal::Handle<v8::internal::FixedArrayBase>) [/usr/local/bin/node]
 8: v8::internal::ArrayConstructInitializeElements(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Arguments*) [/usr/local/bin/node]
 9: v8::internal::(anonymous namespace)::ArrayConstructorCommon(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::AllocationSite>, v8::internal::Arguments*) [/usr/local/bin/node]
10: v8::internal::Runtime_ArrayConstructor(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x33a658a079a7
Abort trap: 6
```

**Comment by hyj1991** [comment]
@gjc9620 你看到的下降实际上是 ```new Array``` 这个临时对象被回收了而已。因为真正被持有无法释放的是 ```new Array().join``` 后的字符串，而 ```new Array``` 得到的数组对象本身是可以被回收的。你可以把你的例子中的 ```join('*')``` 去掉，这样每次得到的 ```new Array``` 就被直接引用无法释放了，这时候可以看到内存是只增不减的

**Comment by hyj1991** [comment]
@gjc9620 你这个问题我觉得可以分两个方面讨论下：

* 看到的回收一部分是由于：直接被持有无法释放的是 ```new Array().join("*")``` 后的字符串，所以 ```new Array()``` 得到的临时数组对象是可以被释放的。

* 这里把 ```new Array().join("*")``` 改为 ```new Array()``` 后，即直接对每次生成的数组对象直接引用，依旧能回收的原因在于你写的 ```thething = theing || {}``` ，实际上例子中的泄漏产生的原因是 ```thething``` 每次指向一个新生成的对象，并且这个对象中包含一个函数 ```someMethod``` 又指向上次循环前的 ```thething```，导致的内存泄漏。而你修改后，只有第一次会生成新对象，后面的 ```thething``` 其实一直指向的是自己，那么就相当于每次循环只做了 ```thething``` 对象里面属性的重新赋值而已，自然重新赋值后之前的 ```new Array()``` 对象或者 ```new Array().join()``` 字符串就能被回收了，也就不会产生内存泄漏~

有误之处还请指正

**Comment by gjc9620** [comment]
@hyj1991 
`从而导致 theThing 对象中的 someMethod 函数隐式地持有了 泄漏变量 的引用。`
为什么someMethod会隐式持有呢？他并没有用到任何外部变量呀

**Comment by gjc9620** [comment]
@hyj1991 
```
  let unused = function () {
    if (泄漏变量)
      console.log("hi")
  };
```
话说回来这个unused并没有使用 不会被GC清除吗？这个问题似乎很复杂和GC如何执行有关

**Comment by hyj1991** [comment]
第一个问题，本来 ```theThing``` 每次tick时指向新对象，那么 ```theThing``` 指向的老对象因为没人持有它的引用了应该会被回收，但是这里恰恰因为 ```新对象->someMethod->泄漏变量->老thething->老对象``` 的链式引用关系 导致老对象永远被持有所以无法释放掉。至于 ```someMethod``` 为什么会引用到 ```泄漏变量``` 就是你的第二个问题了。

第二个问题：你可以仔细看看我的第一个回答：实际上同一个作用域生成的闭包对象是被该作用域中所有下一级作用域共同持有的，正是因为 ```unused``` 使用到了 ```泄漏变量```，所以导致 ```replaceThing```这一级的函数作用域中的闭包对象包含了 ```泄漏变量``` ，而 ```theThing``` 持有了 ```someMethod```，```someMethod``` 定义的函数作用域由持有上述的闭包对象，所以虽然在 ```someMethod``` 中 根本没有使用到 ```泄漏变量```，也会隐式地持有。

**Comment by hyj1991** [comment]
@gjc9620 
至于你说的和GC机制有关，怎么回收肯定是GC机制，但是这里 ```泄漏变量``` 无法释放其实也是因为有对象一直在引用它，所以GC在这个问题上没有什么特殊处理的部分

**Comment by aogg** [comment]
@hyj1991 其实  **隐式地持有变量** 和 **显式地持有变量**  会导致什么或者说有什么区别？

这个内存泄漏问题是因为**同时存在两个函数**与一个**不断变化引用的新对象变量**，其中两个函数一个**显式持有**一个**隐式持有**（满足这三个条件就会导致内存泄漏）。
而上面所有解决方案都是为了减少这个三个条件中的一个。假设新变量的逻辑不改，那就只有从两个函数入手，可为什么去掉```unused```函数的 **显式持有变量**  就可以解决内存泄漏这个问题呢？它还不是 **隐式地持有变量** 吗？

**Comment by gjc9620** [comment]
@hyj1991
请问隐式地持有变量 有相关引用或者代码吗 想了解一下相关

**Comment by hyj1991** [comment]
隐式还是显式只是一个说法罢了，实际上就是js闭包对象除了保持一条指向上一级作用域闭包对象的引用外，还会包含所有下面作一级域使用到的本作用域定义的变量，看这段吧：

> In V8, once there is any closure in the context, the context will be attached to every function, even for those who don’t reference the context at all

**Comment by gjc9620** [comment]
@hyj1991   谢谢 请问文章出处?

**Comment by Lellansin** [comment]
Feel free to reopen.

**Comment by zwmmm** [comment]
```js
var replaceThing = function () {
    console.log(process.memoryUsage().heapUsed);
};
setInterval(replaceThing, 1000);
```
![image](https://user-images.githubusercontent.com/30194521/60709620-7836e700-9f43-11e9-9dc9-5bfdd3d47581.png)
这是为什么？

**Comment by Lellansin** [comment]
> ```js
> var replaceThing = function () {
>     console.log(process.memoryUsage().heapUsed);
> };
> setInterval(replaceThing, 1000);
> ```
> 
> ![image](https://user-images.githubusercontent.com/30194521/60709620-7836e700-9f43-11e9-9dc9-5bfdd3d47581.png)
> 这是为什么？

观察的频率太低了，你把 1000 改成 10 试试。

**Comment by zwmmm** [comment]
@Lellansin 和频率有什么关系？难道内存会自己慢慢增长？

**Comment by hsiaosiyuan0** [comment]
如果 v8 中的实现细节真的如 @hyj1991 大佬说的那样，那我觉得把这个当做是 v8 的缺陷来说比较好。

首先闭包的基本概念是：

1. 变量可以被它作用域下的闭包所捕获：

```js
function f() {
  let a = 1
  return function () { console.log(a) }
}
```

上面代码中 `return` 语句在创建函数对象的时候，会将 `a` 捕获到与之关联的闭包中，不过此时闭包尚未将 `a` 拷贝到内部，当 `a` 离开自己的作用域时，即函数调用结束时，会将 `a` 拷贝到闭包中。

2. 变量在被作用域下的多个闭包所同时捕获的时候，以共享的形式存在于各个闭包中，也就是被捕获变量有能够被共享的特性：

```js
function f() {
  let a = 1
  return [
    function () { a++ },
    function () { console.log(a) }
  ]
}
const [f1, f2] = f();
f1();
f2();
```

上面代码中 `return` 语句创建了两个函数，当然也创建了与两个函数各自相关联的闭包。`a` 将会以一个被这两个闭包所共享的形式存在。

说回 JS 中引入闭包的目的，就是为了让作为一等公民的函数、也能继续沿用词法作用域。在此之后衍生出来的比如模拟私有变量之类，都只能算作是用途。

3. 闭包的生命周期，与那个与之关联的函数是一样的

这是因为闭包被创建了之后，除了与之关联的函数，再没有路径可以访问到它。所以只有函数对象被标记为垃圾对象，与之关联的闭包才会变为垃圾对象。当然并不是函数对象成了垃圾之后，闭包中的内容就都成了垃圾，考虑被捕获的变量具有共享的特性，只有当共享它的所有闭包都成了垃圾时，那个被捕获的共享对象才会成为垃圾。

回到例子中的代码：

```js
var theThing = null
var replaceThing = function () {
  var originalThing = theThing
  var unused = function () {  // closure1
    if (originalThing)
      console.log("hi")
  }
  theThing = {
    longStr: new Array(1000000).join('*'),
    someMethod: function () { // closure2
      console.log('a')
    }
  };
};
setInterval(replaceThing, 1000)
```

按照我上面的描述，这里应该有两个闭包，分别是 `closure1` 和 `closure2`，`closure1` 会捕获栈上的 `originalThing` 而 `closure2` 并没有捕获栈上的内容。

如果是分开的两个闭包，那么很明显并不会导致内存泄露，因为 closure1 会因为 `unused` 的释放而被释放。

而 v8 的实现中，将 `closure1` 和 `closure2` 合二为一，这样就导致原本 `closure2` 根本没有想捕获的变量被意外的捕获了。

从技术来说，即使合二为一了，也应该能够做到 `unused` 释放时，把 `originalThing` 也给释放了，因为是词法作用域，所以引擎在解析阶段就能够知道 `someMethod` 完全不会用到 `originalThing`。但是目前 v8 的实现还做不到这点，所以在不发生内存泄露的情况下，「合N为1」是相安无事的，因为对于 `someMethod` 而言反正它不想也不能用到 `originalThing`。可一旦发生了存在泄露的操作，调试起来还是得消磨不少时间，而且这个泄露有引擎实现的一半的功劳在里面。

为了再验证一下其他语言或者引擎对闭包的实现，我分别尝试了 CLua 和 quickjs

同样闭包的概念在 lua 中也有，CLua 的实现不会导致内存泄露：

```lua
function createArray(size)
  local a = {}
  for i=1,size do
    a[i] = 0
  end
  return a
end


local theThing = nil
local replaceThing = function ()
  local originalThing = theThing
  local unused = function ()
    if originalThing then
      print('hi');
    end
  end
  theThing = {
    longStuff = createArray(1 << 20);
    someMethod = function ()
      print('a')
    end
  }
end

while(true) do
  replaceThing()
end
```

在最新的 [quickjs](https://bellard.org/quickjs/quickjs.html) 中执行等价代码，也不会有内存泄露：

```js
var theThing = null;
var replaceThing = function () {
  var a = theThing;
  var unused = function () {
    if (a)
      console.log("hi");
  };
  theThing = {
    longStr: new Array(1 << 20).join('*'),
    someMethod: function () {
      console.log('a');
    }
  };
};

while(true) {
  replaceThing();
}
```

有错误的话还请指正。

**Comment by lizy0329** [comment]
不用这么复杂, 看一张图就明白：

![企业微信截图_20200915182852.png](https://i.loli.net/2020/09/15/dDXlSq8AFMHgro5.png)

红色：replaceThing 生成的闭包
绿色：对象引用指针
灰色：断掉的指针
N：theThing = null
T：theThing = 新对象

由于“泄”的指针在刚开始指向（theThing = null），随后（theThing = 新对象），“泄”的指针马上断开旧的指向，指向新的对象，导致 GC 一直清除不掉

**Comment by robbiemie** [comment]
灵魂画手

**Comment by guohaoyun** [comment]
> 如果 v8 中的实现细节真的如 @hyj1991 大佬说的那样，那我觉得把这个当做是 v8 的缺陷来说比较好。

我用Node8版本测试有内存泄露问题，但是Node12没有。可能确实是当时版本的一个缺陷，有人能找到相关更新修复说明吗。

**Comment by shanzhangf123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
