### ISSUE TITLE
异步的 reduce

### ISSUE THREAD

**Issue by UlricGan** [ElemeFE/node-interview#9]
> 如何实现一个异步的 reduce? (注:不是异步完了之后同步 reduce) 

```
function reduce(arr, cb, initial = null) {
	function iterator(res, vals, index) {
		if (vals.length == 1) return cb(res, vals[0], index)
		
		return cb(res, vals[0], index).then((n) => iterator(n, vals.slice(1), index + 1))
	}
	
	if (initial) {
		return iterator(initial, arr, 1)
	} else {
		return iterator(arr[0], arr.slice(1), 0)	
	}
}

// 测试用例
function cb(res, i, index) {
	return new Promise(function (resolve, reject) {
		setTimeout(() => {
			resolve(res + i)
		}, 1000)
	})
}

reduce([1, 2, 3, 4, 5], cb)
reduce([1, 2, 3, 4, 5], cb, 10)
```

题意应该没理解错吧？

**Comment by Lellansin** [comment]
没错, doge

**Comment by Lellansin** [comment]
Feel free to reopen

**Comment by hanhuizhu** [comment]
Array.prototype.reduceAsync = async function (cb, initvalue) {
    try {
        let arr = this;
        if (initvalue) {
            let arg1 = initvalue;
            await Promise.all(arr.map(async(value,index)=>{
                let back = await (new Promise((resolve, reject) => {
                    try {
                        setTimeout(function () {
                            arg1 = cb(arg1, value, index, arr);
                            resolve('');
                        }, 0);
                    } catch (e) {
                        reject(e);
                    }
                }));
                return back;
            }));
            return arg1;
        } else {
            let arg1 = arr[0];
            arr.shift();
            await Promise.all(arr.map(async(value,index)=>{
                let back = await (new Promise((resolve, reject) => {
                    try {
                        setTimeout(function () {
                            arg1 = cb(arg1, value, index, arr);
                            resolve('');
                        }, 0);
                    } catch (e) {
                        reject(e);
                    }
                }));
                return back;
            }));
            return arg1;
        }

    } catch (e) {
        console.log(e);
    }
}

let a = [1, 2, 3, 4, 5];
a.reduceAsync((arg1, arg2) => {
    return arg1 + arg2;
}).then(value=>{
    console.log(value);
});

**Comment by hanhuizhu** [comment]
```
Array.prototype.reduceAsync = async function (cb, initvalue) {
    try {
        let arr = this;
        if (initvalue) {
            let arg1 = initvalue;
            await Promise.all(arr.map(async(value,index)=>{
                let back = await (new Promise((resolve, reject) => {
                    try {
                        setTimeout(function () {
                            arg1 = cb(arg1, value, index, arr);
                            resolve('');
                        }, 0);
                    } catch (e) {
                        reject(e);
                    }
                }));
                return back;
            }));
            return arg1;
        } else {
            let arg1 = arr[0];
            arr.shift();
            await Promise.all(arr.map(async(value,index)=>{
                let back = await (new Promise((resolve, reject) => {
                    try {
                        setTimeout(function () {
                            arg1 = cb(arg1, value, index, arr);
                            resolve('');
                        }, 0);
                    } catch (e) {
                        reject(e);
                    }
                }));
                return back;
            }));
            return arg1;
        }

    } catch (e) {
        console.log(e);
    }
}

let a = [1, 2, 3, 4, 5];
a.reduceAsync((arg1, arg2) => {
    return arg1 + arg2;
}).then(value=>{
    console.log(value);
});
```

**Comment by qq8282661** [comment]
`Array.prototype.asyncReduce = async function (cb, initialValue) {
  let accumulator = this[0];
  let index = 1;
  if (initialValue !== undefined) {
    accumulator = initialValue;
    index = 0;
  }
  for (index; index < this.length; index++) {
    accumulator = await cb(accumulator, this[index], index, this);
  }
  return accumulator;
};

[1, 2, 3].asyncReduce(async (acc, current) => acc + current, 4).then((res) => console.log(res));`

**Comment by qq8282661** [comment]
```js
Array.prototype.asyncReduce = async function (cb, initialValue) {
  let accumulator = this[0];
  let index = 1;
  if (initialValue !== undefined) {
    accumulator = initialValue;
    index = 0;
  }
  for (index; index < this.length; index++) {
    accumulator = await cb(accumulator, this[index], index, this);
  }
  return accumulator;
};

[1, 2, 3].asyncReduce(async (acc, current) => acc + current, 4).then((res) => console.log(res));
```
